name: CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release distributables for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.13.0
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Electron Builder
        uses: samuelmeuli/action-electron-builder@v1.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
